#单个玩家发起投票间隔（单位秒）
interval: 100
#投票时限（单位秒）
TimeLimit: 30
#判定系数（该值可以为小数）
#赞同人数*coefficient > 反对人数 时判定投票结果为成功，否则为不成功
coefficient: 1.0
#投票标题
#%yes%同意人数  %no%反对人数 %player%命令执行目标 %cmd%命令名称
Title: "同意&2%yes%&f人--对%player%执行%cmd%--反对&c%no%&f人"
#命令列表
#%player%表示目标玩家
Commands:
  #命令名称为[杀死]
  杀死:
    command: "kill %player%"
  封禁:
    command: "ban %player%"